import React, { useState } from 'react';
import { Card, StatusDot, ProgressBar, Badge, Button, Modal } from '../components/UIComponents';
import { MOCK_PROJECTS, MOCK_ARTIFACTS } from '../constants';
import { Activity, Cpu, Zap, Clock, ArrowRight, Download, Share2 } from 'lucide-react';
import { Artifact } from '../types';
import { useAgents } from '../context/AgentContext';

export const Mission: React.FC = () => {
  const { agents } = useAgents();
  const [selectedArtifact, setSelectedArtifact] = useState<Artifact | null>(null);

  const activeAgentsCount = agents.filter(a => a.status === 'active' || a.status === 'thinking').length;

  const renderArtifactPreview = (artifact: Artifact) => {
     if (artifact.type === 'image') {
       return (
         <div className="flex flex-col items-center">
            <div className="w-full aspect-square md:aspect-video bg-neutral-900 rounded-lg overflow-hidden mb-4 border border-neutral-800">
               <img src={artifact.url} alt={artifact.name} className="w-full h-full object-cover" />
            </div>
            <div className="flex gap-4">
              <Button variant="secondary" icon={<Download size={16} />}>Download</Button>
              <Button variant="secondary" icon={<Share2 size={16} />}>Share</Button>
            </div>
         </div>
       );
     }
     
     if (artifact.type === 'code') {
       return (
         <div className="bg-neutral-900 rounded-lg p-4 font-mono text-sm text-neutral-300 border border-neutral-800 overflow-x-auto">
            <pre>{`// ${artifact.name}
// Generated by Code-Prime

import { AuthAdapter } from '@hydra/core';

export class BiometricAuth implements AuthAdapter {
  async authenticate(signature: string): Promise<boolean> {
    const isValid = await verifySignature(signature);
    if (isValid) {
      console.log('Access Granted');
      return true;
    }
    return false;
  }
}`}</pre>
         </div>
       );
     }

     return (
       <div className="p-8 bg-neutral-900/50 rounded-lg text-center border border-neutral-800 border-dashed">
          <p className="text-neutral-400 italic">Document preview not available in this version.</p>
       </div>
     );
  };

  return (
    <div className="p-6 space-y-6 overflow-y-auto h-full pb-20">
      
      {/* Artifact Modal */}
      <Modal 
        isOpen={!!selectedArtifact} 
        onClose={() => setSelectedArtifact(null)} 
        title={selectedArtifact?.name.toUpperCase()}
      >
        {selectedArtifact && renderArtifactPreview(selectedArtifact)}
      </Modal>

      {/* Top Stats Row */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="bg-surface-dim border-neutral-800/50">
           <div className="flex items-center gap-3">
             <div className="p-2 bg-amber-500/10 rounded-lg text-amber-500">
               <Zap size={20} />
             </div>
             <div>
               <p className="text-xs text-neutral-500 font-mono uppercase">System Power</p>
               <p className="text-xl font-mono font-bold text-neutral-200">1,247 W</p>
             </div>
           </div>
        </Card>
        <Card className="bg-surface-dim border-neutral-800/50">
           <div className="flex items-center gap-3">
             <div className="p-2 bg-purple-500/10 rounded-lg text-purple-500">
               <Cpu size={20} />
             </div>
             <div>
               <p className="text-xs text-neutral-500 font-mono uppercase">VRAM Usage</p>
               <p className="text-xl font-mono font-bold text-neutral-200">42 / 56 GB</p>
             </div>
           </div>
        </Card>
        <Card className="bg-surface-dim border-neutral-800/50">
           <div className="flex items-center gap-3">
             <div className="p-2 bg-emerald-500/10 rounded-lg text-emerald-500">
               <Activity size={20} />
             </div>
             <div>
               <p className="text-xs text-neutral-500 font-mono uppercase">Active Agents</p>
               <p className="text-xl font-mono font-bold text-neutral-200">{activeAgentsCount} / {agents.length}</p>
             </div>
           </div>
        </Card>
        <Card className="bg-surface-dim border-neutral-800/50">
           <div className="flex items-center gap-3">
             <div className="p-2 bg-cyan-500/10 rounded-lg text-cyan-500">
               <Clock size={20} />
             </div>
             <div>
               <p className="text-xs text-neutral-500 font-mono uppercase">Uptime</p>
               <p className="text-xl font-mono font-bold text-neutral-200">14d 03h</p>
             </div>
           </div>
        </Card>
      </div>

      {/* Agents & Projects Split */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Active Agents (2 Cols) */}
        <div className="lg:col-span-2 space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-mono font-semibold text-neutral-200 flex items-center gap-2">
              <span className="text-emerald-500">●</span> ACTIVE_AGENTS
            </h2>
            <Button variant="ghost" size="sm" className="text-xs">View All</Button>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {agents.slice(0, 4).map(agent => (
              <Card key={agent.id} className="hover:border-emerald-500/30 transition-colors cursor-pointer group">
                <div className="flex justify-between items-start mb-3">
                  <div className="flex items-center gap-2">
                    <StatusDot status={agent.status} />
                    <span className="font-semibold text-neutral-200 group-hover:text-emerald-400 transition-colors">{agent.name}</span>
                  </div>
                  <Badge variant={agent.type === 'research' ? 'cyan' : agent.type === 'coding' ? 'purple' : 'neutral'}>
                    {agent.type}
                  </Badge>
                </div>
                
                <div className="space-y-3">
                  <div>
                     <p className="text-xs text-neutral-500 mb-1">Current Task</p>
                     <p className="text-sm text-neutral-300 line-clamp-1">{agent.task}</p>
                  </div>
                  
                  <div>
                    <div className="flex justify-between text-xs text-neutral-500 mb-1 font-mono">
                      <span>PROGRESS</span>
                      <span>{agent.progress}%</span>
                    </div>
                    <ProgressBar value={agent.progress} colorClass={agent.status === 'active' ? 'bg-emerald-500' : 'bg-cyan-500'} />
                  </div>
                  
                  <div className="pt-2 border-t border-neutral-800 flex justify-between items-center text-xs font-mono text-neutral-600">
                    <span>{agent.model}</span>
                    <span>{agent.uptime}</span>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </div>

        {/* Recent Activity / Outputs (1 Col) */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-mono font-semibold text-neutral-200">RECENT_ARTIFACTS</h2>
          </div>
          
          <Card className="h-[420px] overflow-hidden flex flex-col">
            <div className="flex-1 overflow-y-auto space-y-0 divide-y divide-neutral-800">
              {MOCK_ARTIFACTS.map(artifact => (
                <div 
                  key={artifact.id} 
                  className="p-4 hover:bg-surface-raised transition-colors cursor-pointer flex items-start gap-3 group"
                  onClick={() => setSelectedArtifact(artifact)}
                >
                  <div className="h-10 w-10 rounded bg-neutral-800 flex items-center justify-center shrink-0 group-hover:bg-neutral-700 transition-colors">
                    {artifact.type === 'image' && <span className="text-lg">🖼️</span>}
                    {artifact.type === 'code' && <span className="text-lg">💻</span>}
                    {artifact.type === 'document' && <span className="text-lg">📄</span>}
                  </div>
                  <div className="flex-1 min-w-0">
                    <h4 className="text-sm font-medium text-neutral-300 truncate group-hover:text-emerald-400 transition-colors">{artifact.name}</h4>
                    <p className="text-xs text-neutral-500 mt-0.5">{artifact.timestamp}</p>
                  </div>
                  <Button variant="ghost" size="sm" className="opacity-0 group-hover:opacity-100 p-1">
                    <ArrowRight size={14} />
                  </Button>
                </div>
              ))}
              
              {/* Timeline Items Mock */}
              <div className="p-3 bg-neutral-900/30">
                 <p className="text-xs font-mono text-neutral-500 mb-2 uppercase tracking-wider">System Log</p>
                 <div className="space-y-3 pl-2 border-l border-neutral-800">
                   <div className="pl-3 relative">
                     <div className="absolute -left-[5px] top-1.5 w-2 h-2 rounded-full bg-emerald-500" />
                     <p className="text-xs text-neutral-400">Agent <span className="text-emerald-400">Research-Alpha</span> completed quantum analysis task.</p>
                     <span className="text-[10px] text-neutral-600">2m ago</span>
                   </div>
                   <div className="pl-3 relative">
                     <div className="absolute -left-[5px] top-1.5 w-2 h-2 rounded-full bg-amber-500" />
                     <p className="text-xs text-neutral-400">GPU Temp Warning: Node-02 reached 82°C.</p>
                     <span className="text-[10px] text-neutral-600">15m ago</span>
                   </div>
                 </div>
              </div>
            </div>
          </Card>
        </div>
      </div>
      
      {/* Projects Row */}
      <div className="space-y-4">
        <h2 className="text-lg font-mono font-semibold text-neutral-200">ACTIVE_PROJECTS</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
           {MOCK_PROJECTS.map(project => (
             <Card key={project.id} className="hover:border-cyan-500/30 transition-colors">
               <div className="flex justify-between items-start mb-2">
                 <h3 className="font-semibold text-neutral-200">{project.name}</h3>
                 <StatusDot status={project.status === 'active' ? 'active' : 'paused'} />
               </div>
               <p className="text-sm text-neutral-400 mb-4 h-10 line-clamp-2">{project.description}</p>
               
               <div className="space-y-2">
                 <div className="flex justify-between text-xs text-neutral-500 font-mono">
                   <span>COMPLETION</span>
                   <span>{project.progress}%</span>
                 </div>
                 <ProgressBar value={project.progress} colorClass="bg-cyan-500" />
               </div>
               
               <div className="mt-4 flex items-center justify-between text-xs">
                 <Badge variant="neutral">{project.agentCount} Agents</Badge>
                 <span className="text-neutral-600 font-mono">{project.lastUpdated}</span>
               </div>
             </Card>
           ))}
        </div>
      </div>

    </div>
  );
};
