import React, { useState } from 'react';
import { Card, StatusDot, ProgressBar, Badge, Button, Modal } from '../components/UIComponents';
import { Activity, Cpu, Zap, Clock, ArrowRight, Download, Share2, RefreshCw, Wifi, WifiOff } from 'lucide-react';
import { Artifact } from '../types';
import { useAgents } from '../context/AgentContext';
import { useDashboardData } from '../context/DashboardDataContext';

export const Mission: React.FC = () => {
  const { agents, isLoading: agentsLoading, isConnected } = useAgents();
  const { projects, stats, alerts, isLoading: dataLoading, refreshAll } = useDashboardData();
  const [selectedArtifact, setSelectedArtifact] = useState<Artifact | null>(null);

  const activeAgentsCount = agents.filter(a => a.status === 'active' || a.status === 'thinking').length;
  const isLoading = agentsLoading || dataLoading;

  // Generate artifacts from recent agent activity
  const recentArtifacts: Artifact[] = agents
    .filter(a => a.task && a.task !== 'Awaiting assignment')
    .slice(0, 3)
    .map((a, i) => ({
      id: `artifact-${i}`,
      type: a.type === 'coding' ? 'code' : a.type === 'creative' ? 'image' : 'document',
      name: a.task.slice(0, 40),
      timestamp: a.uptime || 'recently',
      url: '',
    }));

  const renderArtifactPreview = (artifact: Artifact) => {
    if (artifact.type === 'image') {
      return (
        <div className="flex flex-col items-center">
          <div className="w-full aspect-square md:aspect-video bg-neutral-900 rounded-lg overflow-hidden mb-4 border border-neutral-800">
            <div className="w-full h-full flex items-center justify-center text-neutral-600">
              Image preview not available
            </div>
          </div>
          <div className="flex gap-4">
            <Button variant="secondary" icon={<Download size={16} />}>Download</Button>
            <Button variant="secondary" icon={<Share2 size={16} />}>Share</Button>
          </div>
        </div>
      );
    }

    if (artifact.type === 'code') {
      return (
        <div className="bg-neutral-900 rounded-lg p-4 font-mono text-sm text-neutral-300 border border-neutral-800 overflow-x-auto">
          <pre>{`// ${artifact.name}
// Generated by Code-Prime

// Code preview not available
// View in IDE for full source`}</pre>
        </div>
      );
    }

    return (
      <div className="p-8 bg-neutral-900/50 rounded-lg text-center border border-neutral-800 border-dashed">
        <p className="text-neutral-400 italic">Document preview not available in this version.</p>
      </div>
    );
  };

  return (
    <div className="p-6 space-y-6 overflow-y-auto h-full pb-20">

      {/* Artifact Modal */}
      <Modal
        isOpen={!!selectedArtifact}
        onClose={() => setSelectedArtifact(null)}
        title={selectedArtifact?.name.toUpperCase()}
      >
        {selectedArtifact && renderArtifactPreview(selectedArtifact)}
      </Modal>

      {/* Connection Status Bar */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2 text-sm">
          {isConnected ? (
            <>
              <Wifi size={16} className="text-emerald-500" />
              <span className="text-emerald-500 font-mono">LIVE</span>
            </>
          ) : (
            <>
              <WifiOff size={16} className="text-amber-500" />
              <span className="text-amber-500 font-mono">POLLING</span>
            </>
          )}
        </div>
        <Button
          variant="ghost"
          size="sm"
          onClick={refreshAll}
          icon={<RefreshCw size={14} className={isLoading ? 'animate-spin' : ''} />}
        >
          Refresh
        </Button>
      </div>

      {/* Top Stats Row */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="bg-surface-dim border-neutral-800/50">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-amber-500/10 rounded-lg text-amber-500">
              <Zap size={20} />
            </div>
            <div>
              <p className="text-xs text-neutral-500 font-mono uppercase">System Power</p>
              <p className="text-xl font-mono font-bold text-neutral-200">
                {stats?.systemPower ? `${stats.systemPower.toLocaleString()} W` : '-- W'}
              </p>
            </div>
          </div>
        </Card>
        <Card className="bg-surface-dim border-neutral-800/50">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-purple-500/10 rounded-lg text-purple-500">
              <Cpu size={20} />
            </div>
            <div>
              <p className="text-xs text-neutral-500 font-mono uppercase">VRAM Usage</p>
              <p className="text-xl font-mono font-bold text-neutral-200">
                {stats ? `${stats.vramUsed} / ${stats.vramTotal} GB` : '-- / -- GB'}
              </p>
            </div>
          </div>
        </Card>
        <Card className="bg-surface-dim border-neutral-800/50">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-emerald-500/10 rounded-lg text-emerald-500">
              <Activity size={20} />
            </div>
            <div>
              <p className="text-xs text-neutral-500 font-mono uppercase">Active Agents</p>
              <p className="text-xl font-mono font-bold text-neutral-200">{activeAgentsCount} / {agents.length}</p>
            </div>
          </div>
        </Card>
        <Card className="bg-surface-dim border-neutral-800/50">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-cyan-500/10 rounded-lg text-cyan-500">
              <Clock size={20} />
            </div>
            <div>
              <p className="text-xs text-neutral-500 font-mono uppercase">Uptime</p>
              <p className="text-xl font-mono font-bold text-neutral-200">{stats?.uptime || '-- --'}</p>
            </div>
          </div>
        </Card>
      </div>

      {/* Agents & Projects Split */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

        {/* Active Agents (2 Cols) */}
        <div className="lg:col-span-2 space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-mono font-semibold text-neutral-200 flex items-center gap-2">
              <span className="text-emerald-500">●</span> ACTIVE_AGENTS
            </h2>
            <Button variant="ghost" size="sm" className="text-xs">View All</Button>
          </div>

          {isLoading ? (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {[1, 2, 3, 4].map(i => (
                <Card key={i} className="animate-pulse">
                  <div className="h-4 bg-neutral-800 rounded w-2/3 mb-3" />
                  <div className="h-3 bg-neutral-800 rounded w-full mb-2" />
                  <div className="h-2 bg-neutral-800 rounded w-full" />
                </Card>
              ))}
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {agents.slice(0, 4).map(agent => (
                <Card key={agent.id} className="hover:border-emerald-500/30 transition-colors cursor-pointer group">
                  <div className="flex justify-between items-start mb-3">
                    <div className="flex items-center gap-2">
                      <StatusDot status={agent.status} />
                      <span className="font-semibold text-neutral-200 group-hover:text-emerald-400 transition-colors">{agent.name}</span>
                    </div>
                    <Badge variant={agent.type === 'research' ? 'cyan' : agent.type === 'coding' ? 'purple' : 'neutral'}>
                      {agent.type}
                    </Badge>
                  </div>

                  <div className="space-y-3">
                    <div>
                      <p className="text-xs text-neutral-500 mb-1">Current Task</p>
                      <p className="text-sm text-neutral-300 line-clamp-1">{agent.task}</p>
                    </div>

                    <div>
                      <div className="flex justify-between text-xs text-neutral-500 mb-1 font-mono">
                        <span>PROGRESS</span>
                        <span>{agent.progress}%</span>
                      </div>
                      <ProgressBar value={agent.progress} colorClass={agent.status === 'active' ? 'bg-emerald-500' : 'bg-cyan-500'} />
                    </div>

                    <div className="pt-2 border-t border-neutral-800 flex justify-between items-center text-xs font-mono text-neutral-600">
                      <span>{agent.model}</span>
                      <span>{agent.uptime}</span>
                    </div>
                  </div>
                </Card>
              ))}
            </div>
          )}
        </div>

        {/* Recent Activity / Outputs (1 Col) */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-mono font-semibold text-neutral-200">RECENT_ARTIFACTS</h2>
          </div>

          <Card className="h-[420px] overflow-hidden flex flex-col">
            <div className="flex-1 overflow-y-auto space-y-0 divide-y divide-neutral-800">
              {recentArtifacts.length === 0 ? (
                <div className="p-8 text-center text-neutral-500">
                  <p>No recent artifacts</p>
                  <p className="text-xs mt-1">Artifacts will appear when agents complete tasks</p>
                </div>
              ) : (
                recentArtifacts.map(artifact => (
                  <div
                    key={artifact.id}
                    className="p-4 hover:bg-surface-raised transition-colors cursor-pointer flex items-start gap-3 group"
                    onClick={() => setSelectedArtifact(artifact)}
                  >
                    <div className="h-10 w-10 rounded bg-neutral-800 flex items-center justify-center shrink-0 group-hover:bg-neutral-700 transition-colors">
                      {artifact.type === 'image' && <span className="text-lg">🖼️</span>}
                      {artifact.type === 'code' && <span className="text-lg">💻</span>}
                      {artifact.type === 'document' && <span className="text-lg">📄</span>}
                    </div>
                    <div className="flex-1 min-w-0">
                      <h4 className="text-sm font-medium text-neutral-300 truncate group-hover:text-emerald-400 transition-colors">{artifact.name}</h4>
                      <p className="text-xs text-neutral-500 mt-0.5">{artifact.timestamp}</p>
                    </div>
                    <Button variant="ghost" size="sm" className="opacity-0 group-hover:opacity-100 p-1">
                      <ArrowRight size={14} />
                    </Button>
                  </div>
                ))
              )}

              {/* System Log from Alerts */}
              <div className="p-3 bg-neutral-900/30">
                <p className="text-xs font-mono text-neutral-500 mb-2 uppercase tracking-wider">System Log</p>
                <div className="space-y-3 pl-2 border-l border-neutral-800">
                  {alerts.length === 0 ? (
                    <p className="text-xs text-neutral-600 pl-3">No recent alerts</p>
                  ) : (
                    alerts.slice(0, 3).map((alert, i) => (
                      <div key={alert.id || i} className="pl-3 relative">
                        <div className={`absolute -left-[5px] top-1.5 w-2 h-2 rounded-full ${alert.severity === 'error' || alert.severity === 'critical' ? 'bg-red-500' :
                            alert.severity === 'warning' ? 'bg-amber-500' : 'bg-emerald-500'
                          }`} />
                        <p className="text-xs text-neutral-400">{alert.message}</p>
                        <span className="text-[10px] text-neutral-600">{alert.timestamp}</span>
                      </div>
                    ))
                  )}
                </div>
              </div>
            </div>
          </Card>
        </div>
      </div>

      {/* Projects Row */}
      <div className="space-y-4">
        <h2 className="text-lg font-mono font-semibold text-neutral-200">ACTIVE_PROJECTS</h2>
        {isLoading ? (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[1, 2, 3].map(i => (
              <Card key={i} className="animate-pulse">
                <div className="h-4 bg-neutral-800 rounded w-2/3 mb-3" />
                <div className="h-3 bg-neutral-800 rounded w-full mb-2" />
                <div className="h-2 bg-neutral-800 rounded w-full" />
              </Card>
            ))}
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {projects.map(project => (
              <Card key={project.id} className="hover:border-cyan-500/30 transition-colors">
                <div className="flex justify-between items-start mb-2">
                  <h3 className="font-semibold text-neutral-200">{project.name}</h3>
                  <StatusDot status={project.status === 'active' ? 'active' : 'paused'} />
                </div>
                <p className="text-sm text-neutral-400 mb-4 h-10 line-clamp-2">{project.description}</p>

                <div className="space-y-2">
                  <div className="flex justify-between text-xs text-neutral-500 font-mono">
                    <span>COMPLETION</span>
                    <span>{project.progress}%</span>
                  </div>
                  <ProgressBar value={project.progress} colorClass="bg-cyan-500" />
                </div>

                <div className="mt-4 flex items-center justify-between text-xs">
                  <Badge variant="neutral">{project.agentCount} Agents</Badge>
                  <span className="text-neutral-600 font-mono">{project.lastUpdated}</span>
                </div>
              </Card>
            ))}
          </div>
        )}
      </div>

    </div>
  );
};
