#!/bin/bash
# Tier 1 Infrastructure Deployment Script
#
# Deploys critical infrastructure components:
# 1. Fixes container healthchecks
# 2. Deploys hydra-health and hydra-alerts services
# 3. Sets up Uptime Kuma monitors
# 4. Activates n8n workflows
#
# Run on hydra-storage (192.168.1.244):
#   scp -r scripts/ root@192.168.1.244:/tmp/hydra-deploy/
#   ssh root@192.168.1.244 "cd /tmp/hydra-deploy && chmod +x *.sh && ./deploy-tier1-infrastructure.sh"

set -euo pipefail

# Configuration
STACK_DIR="/mnt/user/appdata/hydra-stack"
COMPOSE_FILE="${STACK_DIR}/docker-compose.yml"
UPTIME_KUMA_URL="http://localhost:3001"
N8N_URL="http://localhost:5678"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log_section() { echo -e "\n${CYAN}=== $1 ===${NC}\n"; }
log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check we're on hydra-storage
check_environment() {
    log_section "Checking Environment"

    if [[ ! -d "$STACK_DIR" ]]; then
        log_error "Stack directory not found: $STACK_DIR"
        log_error "This script must be run on hydra-storage"
        exit 1
    fi

    if ! command -v docker &> /dev/null; then
        log_error "Docker not found"
        exit 1
    fi

    log_info "Environment check passed"
}

# Deploy hydra-health and hydra-alerts services
deploy_health_services() {
    log_section "Deploying Health Services"

    # Check if services compose file exists
    local services_compose="${STACK_DIR}/docker-compose.services.yml"

    # Create the services compose file
    cat > "$services_compose" << 'EOF'
# Hydra Health Services
# Auto-generated by deploy-tier1-infrastructure.sh

version: "3.9"

services:
  hydra-health:
    image: python:3.11-slim
    container_name: hydra-health
    restart: unless-stopped
    working_dir: /app
    command: >
      bash -c "
        pip install --no-cache-dir fastapi uvicorn httpx pydantic &&
        uvicorn hydra_health.server:app --host 0.0.0.0 --port 8600
      "
    volumes:
      - ${STACK_DIR}/src/hydra_health:/app/hydra_health:ro
    networks:
      - hydra-net
    ports:
      - "8600:8600"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8600/live || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      com.hydra.stack: "core"
      com.hydra.service: "health-aggregator"

  hydra-alerts:
    image: python:3.11-slim
    container_name: hydra-alerts
    restart: unless-stopped
    working_dir: /app
    command: >
      bash -c "
        pip install --no-cache-dir fastapi uvicorn httpx pydantic &&
        uvicorn hydra_alerts.webhook:app --host 0.0.0.0 --port 9095
      "
    volumes:
      - ${STACK_DIR}/src/hydra_alerts:/app/hydra_alerts:ro
    networks:
      - hydra-net
    ports:
      - "9095:9095"
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL:-}
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9095/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      com.hydra.stack: "core"
      com.hydra.service: "alert-receiver"

networks:
  hydra-net:
    external: true
EOF

    log_info "Created services compose file: $services_compose"

    # Check if source directories exist
    if [[ ! -d "${STACK_DIR}/src/hydra_health" ]]; then
        log_warn "Source directory not found: ${STACK_DIR}/src/hydra_health"
        log_info "Creating source directories..."
        mkdir -p "${STACK_DIR}/src/hydra_health"
        mkdir -p "${STACK_DIR}/src/hydra_alerts"

        # Copy source files if they exist in the project
        if [[ -f "/tmp/hydra-deploy/hydra_health/server.py" ]]; then
            cp -r /tmp/hydra-deploy/hydra_health/* "${STACK_DIR}/src/hydra_health/"
            log_info "Copied hydra_health source files"
        fi
        if [[ -f "/tmp/hydra-deploy/hydra_alerts/webhook.py" ]]; then
            cp -r /tmp/hydra-deploy/hydra_alerts/* "${STACK_DIR}/src/hydra_alerts/"
            log_info "Copied hydra_alerts source files"
        fi
    fi

    # Deploy services
    log_info "Starting hydra-health and hydra-alerts containers..."
    cd "$STACK_DIR"
    docker-compose -f "$services_compose" up -d || {
        log_warn "docker-compose failed, trying docker compose..."
        docker compose -f "$services_compose" up -d
    }

    # Verify deployment
    sleep 10

    if curl -sf http://localhost:8600/health &>/dev/null; then
        log_info "hydra-health is running and healthy"
    else
        log_warn "hydra-health may still be starting..."
    fi

    if curl -sf http://localhost:9095/health &>/dev/null; then
        log_info "hydra-alerts is running and healthy"
    else
        log_warn "hydra-alerts may still be starting..."
    fi
}

# Update existing container healthchecks
update_healthchecks() {
    log_section "Updating Container Healthchecks"

    # Merge healthcheck additions
    local healthchecks_file="${STACK_DIR}/docker-compose.healthchecks.yml"

    if [[ -f "/tmp/hydra-deploy/healthchecks-additions.yml" ]]; then
        cp /tmp/hydra-deploy/healthchecks-additions.yml "$healthchecks_file"
        log_info "Copied healthchecks additions file"
    else
        log_warn "Healthchecks additions file not found in deploy bundle"
    fi

    # List current unhealthy containers
    log_info "Current unhealthy containers:"
    docker ps --filter "health=unhealthy" --format "  - {{.Names}}: {{.Status}}" || true

    log_info "To apply healthcheck fixes, run:"
    log_info "  cd $STACK_DIR"
    log_info "  docker-compose -f docker-compose.yml -f docker-compose.healthchecks.yml up -d"
}

# Setup Uptime Kuma monitors
setup_uptime_kuma() {
    log_section "Setting up Uptime Kuma Monitors"

    # Check if Uptime Kuma is running
    if ! curl -sf "$UPTIME_KUMA_URL" &>/dev/null; then
        log_warn "Uptime Kuma not accessible at $UPTIME_KUMA_URL"
        log_info "Skipping Uptime Kuma setup"
        return
    fi

    log_info "Uptime Kuma is accessible"

    # Check if setup script exists
    if [[ -f "/tmp/hydra-deploy/setup-uptime-kuma.py" ]]; then
        log_info "Running Uptime Kuma setup script..."

        # Install required Python package and run
        docker run --rm --network hydra-net \
            -v /tmp/hydra-deploy/setup-uptime-kuma.py:/app/setup.py:ro \
            python:3.11-slim \
            bash -c "pip install -q uptime-kuma-api && python /app/setup.py" || {
            log_warn "Uptime Kuma setup via script failed"
            log_info "Please configure monitors manually via web UI: $UPTIME_KUMA_URL"
        }
    else
        log_warn "setup-uptime-kuma.py not found"
        log_info "Please configure monitors manually via web UI: $UPTIME_KUMA_URL"
    fi
}

# Activate n8n workflows
activate_n8n_workflows() {
    log_section "Activating n8n Workflows"

    # Check if n8n is running
    if ! curl -sf "$N8N_URL/healthz" &>/dev/null; then
        log_warn "n8n not accessible at $N8N_URL"
        log_info "Skipping n8n workflow activation"
        return
    fi

    log_info "n8n is accessible"

    # n8n requires authentication for API access
    # We'll provide instructions for manual activation

    log_info "n8n workflows need manual activation via web UI:"
    log_info "  1. Go to $N8N_URL"
    log_info "  2. Navigate to each workflow:"
    log_info "     - Daily Health Digest"
    log_info "     - Container Auto-Restart"
    log_info "     - Model Change Notifier"
    log_info "     - Letta Memory Update"
    log_info "  3. Toggle 'Active' switch for each workflow"

    # Check if workflow JSON files exist to import
    if [[ -d "/tmp/hydra-deploy/n8n-workflows" ]]; then
        log_info ""
        log_info "Workflow files available for import:"
        ls -la /tmp/hydra-deploy/n8n-workflows/*.json 2>/dev/null || true
        log_info ""
        log_info "To import workflows:"
        log_info "  1. In n8n, click 'Import from file'"
        log_info "  2. Select workflow JSON files from /tmp/hydra-deploy/n8n-workflows/"
    fi
}

# Verify deployment
verify_deployment() {
    log_section "Verifying Deployment"

    local checks_passed=0
    local checks_total=0

    # Check hydra-health
    ((checks_total++))
    if curl -sf http://localhost:8600/health &>/dev/null; then
        log_info "✓ hydra-health: OK"
        ((checks_passed++))
    else
        log_error "✗ hydra-health: FAILED"
    fi

    # Check hydra-alerts
    ((checks_total++))
    if curl -sf http://localhost:9095/health &>/dev/null; then
        log_info "✓ hydra-alerts: OK"
        ((checks_passed++))
    else
        log_error "✗ hydra-alerts: FAILED"
    fi

    # Check Uptime Kuma
    ((checks_total++))
    if curl -sf http://localhost:3001 &>/dev/null; then
        log_info "✓ Uptime Kuma: OK"
        ((checks_passed++))
    else
        log_warn "○ Uptime Kuma: Not accessible"
    fi

    # Check n8n
    ((checks_total++))
    if curl -sf http://localhost:5678/healthz &>/dev/null; then
        log_info "✓ n8n: OK"
        ((checks_passed++))
    else
        log_warn "○ n8n: Not accessible"
    fi

    # Check Prometheus
    ((checks_total++))
    if curl -sf http://localhost:9090/-/healthy &>/dev/null; then
        log_info "✓ Prometheus: OK"
        ((checks_passed++))
    else
        log_warn "○ Prometheus: Not accessible"
    fi

    # Check Grafana
    ((checks_total++))
    if curl -sf http://localhost:3003/api/health &>/dev/null; then
        log_info "✓ Grafana: OK"
        ((checks_passed++))
    else
        log_warn "○ Grafana: Not accessible"
    fi

    echo ""
    log_info "Verification: $checks_passed/$checks_total checks passed"

    # Show container status summary
    echo ""
    log_info "Container Health Summary:"
    docker ps --format "table {{.Names}}\t{{.Status}}" | head -30

    # Count unhealthy
    local unhealthy_count=$(docker ps --filter "health=unhealthy" --format "{{.Names}}" | wc -l)
    local healthy_count=$(docker ps --filter "health=healthy" --format "{{.Names}}" | wc -l)
    local running_count=$(docker ps --format "{{.Names}}" | wc -l)

    echo ""
    log_info "Running: $running_count | Healthy: $healthy_count | Unhealthy: $unhealthy_count"
}

# Main execution
main() {
    echo -e "${CYAN}"
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║     Hydra Cluster Tier 1 Infrastructure Deployment         ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"

    check_environment
    deploy_health_services
    update_healthchecks
    setup_uptime_kuma
    activate_n8n_workflows
    verify_deployment

    log_section "Deployment Complete"
    log_info "Next steps:"
    log_info "  1. Verify services in Portainer: http://192.168.1.244:9000"
    log_info "  2. Check Grafana dashboards: http://192.168.1.244:3003"
    log_info "  3. Configure Uptime Kuma monitors: http://192.168.1.244:3001"
    log_info "  4. Activate n8n workflows: http://192.168.1.244:5678"
}

main "$@"
