#!/usr/bin/env bash
# SOPS Setup Script for Hydra Cluster
#
# This script:
# 1. Generates age keys from SSH host keys on each node
# 2. Collects public keys and updates .sops.yaml
# 3. Creates initial encrypted secrets files
#
# Prerequisites:
#   - sops installed on all nodes
#   - age installed on all nodes
#   - ssh-to-age installed (go install filippo.io/age/cmd/ssh-to-age@latest)
#   - SSH access to all cluster nodes
#
# Usage:
#   ./setup-sops.sh

set -euo pipefail

# Configuration
NODES=("hydra-ai:192.168.1.250:typhon" "hydra-compute:192.168.1.203:typhon" "hydra-storage:192.168.1.244:root")
SOPS_CONFIG=".sops.yaml"
SECRETS_DIR="secrets"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() {
    echo -e "${BLUE}→${NC} $1"
}

success() {
    echo -e "${GREEN}✓${NC} $1"
}

error() {
    echo -e "${RED}✗${NC} $1"
}

warn() {
    echo -e "${YELLOW}!${NC} $1"
}

header() {
    echo -e "\n${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}\n"
}

# Check prerequisites
check_prerequisites() {
    header "Checking Prerequisites"

    local missing=()

    if ! command -v sops &>/dev/null; then
        missing+=("sops")
    else
        success "sops found: $(sops --version)"
    fi

    if ! command -v age &>/dev/null; then
        missing+=("age")
    else
        success "age found: $(age --version)"
    fi

    if ! command -v ssh-to-age &>/dev/null; then
        warn "ssh-to-age not found locally (will check on nodes)"
    else
        success "ssh-to-age found"
    fi

    if [[ ${#missing[@]} -gt 0 ]]; then
        error "Missing tools: ${missing[*]}"
        echo "Install with:"
        echo "  nix-env -iA nixpkgs.sops nixpkgs.age"
        echo "  go install filippo.io/age/cmd/ssh-to-age@latest"
        exit 1
    fi
}

# Get age public key from SSH host key on a node
get_node_age_key() {
    local name=$1
    local ip=$2
    local user=$3

    log "Getting age public key from $name ($ip)..."

    # Check if ssh-to-age is available on the node
    local has_ssh_to_age=$(ssh -o ConnectTimeout=5 "${user}@${ip}" "which ssh-to-age 2>/dev/null || echo 'not found'")

    if [[ "$has_ssh_to_age" == "not found" ]]; then
        warn "ssh-to-age not found on $name, installing..."
        ssh "${user}@${ip}" "nix-env -iA nixpkgs.ssh-to-age 2>/dev/null || go install filippo.io/age/cmd/ssh-to-age@latest"
    fi

    # Get the age public key
    local age_key=$(ssh "${user}@${ip}" "cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age")

    if [[ -z "$age_key" ]]; then
        error "Failed to get age key from $name"
        return 1
    fi

    echo "$age_key"
    success "Got key for $name: ${age_key:0:20}..."
}

# Collect all keys
collect_keys() {
    header "Collecting Age Public Keys"

    declare -gA NODE_KEYS

    for node_info in "${NODES[@]}"; do
        IFS=':' read -r name ip user <<< "$node_info"

        local key=$(get_node_age_key "$name" "$ip" "$user")
        if [[ -n "$key" ]]; then
            NODE_KEYS["$name"]="$key"
        fi
    done

    echo ""
    log "Collected ${#NODE_KEYS[@]} keys"
}

# Update .sops.yaml with collected keys
update_sops_config() {
    header "Updating SOPS Configuration"

    # Build the comma-separated key list
    local all_keys=""
    for name in "${!NODE_KEYS[@]}"; do
        if [[ -n "$all_keys" ]]; then
            all_keys="${all_keys},\n      ${NODE_KEYS[$name]}"
        else
            all_keys="${NODE_KEYS[$name]}"
        fi
    done

    # Create the new .sops.yaml
    cat > "$SOPS_CONFIG" << EOF
# SOPS Configuration for Hydra Cluster
# Generated by setup-sops.sh on $(date)
#
# Age public keys (derived from SSH host keys):
$(for name in "${!NODE_KEYS[@]}"; do echo "#   $name: ${NODE_KEYS[$name]}"; done)

creation_rules:
  # Cluster-wide secrets (accessible by all nodes)
  - path_regex: secrets/cluster\.yaml\$
    age: >-
      $(echo -e "$all_keys" | sed 's/,$//')

  # hydra-ai specific secrets
  - path_regex: secrets/hydra-ai\.yaml\$
    age: ${NODE_KEYS["hydra-ai"]:-"# key not found"}

  # hydra-compute specific secrets
  - path_regex: secrets/hydra-compute\.yaml\$
    age: ${NODE_KEYS["hydra-compute"]:-"# key not found"}

  # hydra-storage specific secrets
  - path_regex: secrets/hydra-storage\.yaml\$
    age: ${NODE_KEYS["hydra-storage"]:-"# key not found"}

stores:
  yaml:
    indent: 2
EOF

    success "Updated $SOPS_CONFIG"
}

# Create initial secrets file
create_secrets() {
    header "Creating Secrets Files"

    mkdir -p "$SECRETS_DIR"

    # Copy template if it doesn't exist as encrypted
    if [[ ! -f "$SECRETS_DIR/cluster.yaml" ]]; then
        if [[ -f "$SECRETS_DIR/cluster.yaml.template" ]]; then
            cp "$SECRETS_DIR/cluster.yaml.template" "$SECRETS_DIR/cluster.yaml"
            log "Copied template to cluster.yaml"

            # Encrypt it
            log "Encrypting cluster.yaml..."
            if sops -e -i "$SECRETS_DIR/cluster.yaml"; then
                success "Encrypted $SECRETS_DIR/cluster.yaml"
            else
                error "Failed to encrypt cluster.yaml"
            fi
        else
            warn "No template found at $SECRETS_DIR/cluster.yaml.template"
        fi
    else
        warn "cluster.yaml already exists, skipping"
    fi
}

# Distribute keys to nodes
distribute_keys() {
    header "Distributing Age Keys to Nodes"

    for node_info in "${NODES[@]}"; do
        IFS=':' read -r name ip user <<< "$node_info"

        log "Setting up $name..."

        # Ensure age key directory exists
        ssh "${user}@${ip}" "mkdir -p ~/.config/sops/age"

        # Create age key from SSH key (for decryption)
        ssh "${user}@${ip}" "
            if [[ ! -f ~/.config/sops/age/keys.txt ]]; then
                cat /etc/ssh/ssh_host_ed25519_key | ssh-to-age -private-key > ~/.config/sops/age/keys.txt
                chmod 600 ~/.config/sops/age/keys.txt
                echo 'Created age key for decryption'
            else
                echo 'Age key already exists'
            fi
        "

        success "Configured $name"
    done
}

# Test decryption on a node
test_decryption() {
    header "Testing Decryption"

    if [[ ! -f "$SECRETS_DIR/cluster.yaml" ]]; then
        warn "No encrypted secrets to test"
        return
    fi

    local first_node="${NODES[0]}"
    IFS=':' read -r name ip user <<< "$first_node"

    log "Copying encrypted file to $name..."
    scp "$SECRETS_DIR/cluster.yaml" "${user}@${ip}:/tmp/test-secrets.yaml"

    log "Testing decryption on $name..."
    if ssh "${user}@${ip}" "sops -d /tmp/test-secrets.yaml > /dev/null 2>&1"; then
        success "Decryption test passed on $name"
    else
        error "Decryption test failed on $name"
    fi

    # Cleanup
    ssh "${user}@${ip}" "rm -f /tmp/test-secrets.yaml"
}

# Print summary
print_summary() {
    header "Setup Complete"

    echo "SOPS/age encryption is now configured for the Hydra cluster."
    echo ""
    echo "Usage:"
    echo "  Create encrypted secrets:  sops secrets/cluster.yaml"
    echo "  Edit secrets:              sops secrets/cluster.yaml"
    echo "  View decrypted:            sops -d secrets/cluster.yaml"
    echo ""
    echo "On cluster nodes, secrets can be decrypted automatically"
    echo "using the age key derived from the SSH host key."
    echo ""
    echo "Next steps:"
    echo "  1. Edit secrets/cluster.yaml with your actual credentials"
    echo "  2. Commit the encrypted file to git (safe!)"
    echo "  3. Update docker-compose to use sops-decrypted secrets"
}

# Main
main() {
    header "SOPS Setup for Hydra Cluster"

    check_prerequisites
    collect_keys
    update_sops_config
    distribute_keys
    create_secrets
    test_decryption
    print_summary
}

main "$@"
